### PR TITLE
Feat: HomePage

### PR DESCRIPTION
**Pull request by rehanmohiuddin**
- Header
- Carousel
- Carousel With API
- Context for Cat & Products
- Featured Products

### CODE REVIEW

**Review by ishapatell1 — APPROVED** [review]
Hey Rehan, it would be great if you can include a preview of your app. It makes your UI  more understandable, else you did a great job removing all console.logs from the code.

**Comment by rehanmohiuddin** [comment]
> Hey Rehan, it would be great if you can include a preview of your app. It makes your UI more understandable, else you did a great job removing all console.logs from the code.

Preview is there isha please check again

**Review by ArjunGTX — APPROVED** [review]
Everything looks good to go. And thankyou for keeping the PR simple

**Review by Kavita539 — APPROVED** [review]
Everything looks clean and readable. Well maintained and structured code. Great work with the UI, it looks clean and minimal

**Pull request merged**
